 -- Toggles --
_G.kaConn = false
_G.mobKillaura = false
_G.scaffoldEnabled = false
_G.hitboxConn = false
_G.xrayConn = false
_G.BlackCover = false
 -- Configuration --
_G.kaDelay = 0.02
_G.scaffoldDelay = 0.01
_G.hitboxSize = 9
_G.kaTeamCheck = true
